---
- hosts: "bastion"
  become: true
  gather_facts: false  # Optional: If your script doesn't need facts
  vars_files:
    - vars.yaml
  vars:
    kube_api_host: "{{ lookup('cloud.terraform.tf_output', 'kube_api_host', state_file='/Users/igomez/go/src/github.com/terraform-poc/terraform/aws/cluster_nodes/terraform.tfstate') }}"
  tasks:
    - name: Transfer and execute installation script
      script: ./init-cluster.sh
      environment:
        KUBERNETES_VERSION: "{{ kubernetes_version }}"
        KUBE_API_HOST: "{{ kube_api_host }}"
      register: script_result

    - name: Display script output (stdout)
      debug:
        var: script_result.stdout_lines

    - name: Display script errors (stderr) if any
      debug:
        var: script_result.stderr_lines
      when: script_result.rc!= 0

    - name: Check script return code
      debug:
        msg: "Script returned: {{ script_result.rc }}"

    - name: Read file contents into a variable
      raw: cat /etc/rancher/rke2/rke2.yaml
      register: file_contents

    - name: Save file contents locally
      delegate_to: localhost
      run_once: true
      become: no  # Ensure sudo is NOT used
      shell: echo "{{ file_contents.stdout }}" > ./kubeconfig.yaml
